// Generated by playwright-god (mode=static, archetype=static-site, confidence=0.25)
import { test, expect } from "@playwright/test";

test("credential smoke", async ({ page, baseURL }) => {
  // Smoke test: visit the application root and verify it loads without page-level errors.
  const consoleMessages: string[] = [];
  const pageErrors: Error[] = [];

  page.on("console", (msg) => {
    consoleMessages.push(`[${msg.type()}] ${msg.text()}`);
  });
  page.on("pageerror", (error) => {
    pageErrors.push(error);
  });

  await page.goto(baseURL ?? "/", { waitUntil: "domcontentloaded" });
  await expect(page).toHaveURL(/\/?$/);
  await expect(page.locator("body")).toBeVisible();
  expect(pageErrors, `Unexpected page errors:\n${pageErrors.map((e) => e.stack || e.message).join("\n")}\nConsole:\n${consoleMessages.join("\n")}`).toEqual([]);
});