// Generated by playwright-god (mode=static, archetype=static-site, confidence=0.25)
import { test, expect, Page } from "@playwright/test";

type ConsoleEntry = { type: string; text: string };

async function attachPageDiagnostics(page: Page) {
  const consoleMessages: ConsoleEntry[] = [];
  const pageErrors: string[] = [];

  page.on("console", (msg) => {
    consoleMessages.push({ type: msg.type(), text: msg.text() });
  });

  page.on("pageerror", (err) => {
    pageErrors.push(String(err));
  });

  return {
    consoleMessages,
    pageErrors,
    assertNoPageErrors: async () => {
      expect(pageErrors, `Unexpected page errors:\n${pageErrors.join("\n")}`).toEqual([]);
    },
  };
}

async function gotoDesktopShell(page: Page) {
  await page.goto("/");
  await page.waitForLoadState("domcontentloaded");
  await expect(page.getByRole("button", { name: "Repository" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Memory Map" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Flow Graph" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Coverage & Gaps" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Generation" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Codegen Stream" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Dry Run / Inspect" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Audit Log" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Settings" })).toBeVisible();
}

async function openSection(page: Page, name: string) {
  await page.getByRole("button", { name }).click();
  await expect(page.getByRole("heading", { name })).toBeVisible();
}

test.describe("Playwright God desktop shell end-to-end", () => {
  test("navigates the desktop shell and validates repository selection and empty-state CTAs", async ({
    page,
  }) => {
    // Intent: verify the shell loads, primary navigation works, and repository/index empty states are actionable.
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);

    await openSection(page, "Repository");
    await expect(
      page.getByText(/Select a repository to inspect index status|Indexing is required before Memory Map and RAG search can load\./),
    ).toBeVisible();

    const openRepoButton = page.getByRole("button", { name: "Open Repository…" });
    await expect(openRepoButton).toBeVisible();

    const runIndexButton = page.getByRole("button", { name: "Run Index" });
    if (await runIndexButton.isVisible().catch(() => false)) {
      await expect(runIndexButton).toBeEnabled();
    }

    await openSection(page, "Memory Map");
    await expect(
      page.getByText(/No memory map found|Open a repository to view the memory map\./),
    ).toBeVisible();

    const memoryMapRunIndex = page.getByRole("button", { name: "Run Index" });
    if (await memoryMapRunIndex.isVisible().catch(() => false)) {
      await expect(memoryMapRunIndex).toBeEnabled();
    }

    await openSection(page, "Flow Graph");
    await expect(
      page.getByText(/No flow graph found|Open a repository to view the flow graph\./),
    ).toBeVisible();

    await openSection(page, "Coverage & Gaps");
    await expect(
      page.getByText(/Open a repository to view coverage|Loading coverage…|No coverage report found/i),
    ).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });

  test("opens settings and verifies provider resolution and secret-related controls are present", async ({
    page,
  }) => {
    // Intent: validate the settings surface exposes provider/model configuration and effective-resolution UI.
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);
    await openSection(page, "Settings");

    await expect(
      page.getByText(/provider/i).first(),
    ).toBeVisible();

    await expect(
      page.getByText(/model/i).first(),
    ).toBeVisible();

    await expect(
      page.getByText(/OpenAI|Anthropic|Gemini|Template/i).first(),
    ).toBeVisible();

    await expect(
      page.getByText(/effective|resolved|source|repo-dotenv|process env|settings/i).first(),
    ).toBeVisible();

    const saveButton = page.getByRole("button", { name: /save/i });
    if (await saveButton.isVisible().catch(() => false)) {
      await expect(saveButton).toBeEnabled();
    }

    const resetButton = page.getByRole("button", { name: /reset/i });
    if (await resetButton.isVisible().catch(() => false)) {
      await expect(resetButton).toBeVisible();
    }

    await diagnostics.assertNoPageErrors();
  });

  test("covers generation workflow states including disabled-without-repo, prompt entry, and pipeline controls", async ({
    page,
  }) => {
    // Intent: ensure the generation panel exposes the pipeline workflow and safe disabled states before a repo is selected.
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);
    await openSection(page, "Generation");

    await expect(
      page.getByText(/Select a repository in the Repository section to enable the pipeline\./),
    ).toBeVisible();

    const description = page.getByRole("textbox", {
      name: /Description \(optional\)/i,
    });
    await expect(description).toBeVisible();
    await expect(description).toHaveAttribute("placeholder", /What should the next generated test cover\?/);

    await description.fill("login flow");
    await expect(description).toHaveValue("login flow");

    const runPipeline = page.getByRole("button", { name: /Run Pipeline|Running\.\.\./ });
    await expect(runPipeline).toBeDisabled();

    const cancelButton = page.getByRole("button", { name: /Cancel/i });
    if (await cancelButton.isVisible().catch(() => false)) {
      await expect(cancelButton).toBeDisabled();
    }

    await expect(page.getByText(/idle|running|failed|cancelled|succeeded/i).first()).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });

  test("covers RAG search empty state and search form visibility", async ({ page }) => {
    // Intent: verify the RAG section renders either its empty state or a searchable interface without crashing.
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);

    const ragNav = page.getByRole("button", { name: /RAG|Search/i }).first();
    if (await ragNav.isVisible().catch(() => false)) {
      await ragNav.click();
    } else {
      await openSection(page, "Memory Map");
    }

    const emptyState = page.getByText(/No repository index found|Run Index|Open a repository/i);
    const searchBox = page.getByRole("textbox").filter({ has: page.locator(":scope") }).first();

    await expect(emptyState.or(searchBox)).toBeVisible();

    const runIndexButton = page.getByRole("button", { name: "Run Index" });
    if (await runIndexButton.isVisible().catch(() => false)) {
      await expect(runIndexButton).toBeEnabled();
    }

    const searchButton = page.getByRole("button", { name: /Search/i });
    if (await searchButton.isVisible().catch(() => false)) {
      await expect(searchButton).toBeEnabled();
    }

    await diagnostics.assertNoPageErrors();
  });

  test("validates audit log visibility and no-runs state", async ({ page }) => {
    // Intent: confirm the audit log section is reachable and shows a stable empty state when no runs exist.
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);
    await openSection(page, "Audit Log");

    await expect(
      page.getByText(/No runs found in/i),
    ).toBeVisible();

    await expect(page.getByText(".pg_runs/")).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });

  test("validates inspect and output-oriented sections render stable empty or loading states", async ({
    page,
  }) => {
    // Intent: cover inspect/codegen/output surfaces and ensure they present user-readable states instead of errors.
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);

    await openSection(page, "Dry Run / Inspect");
    await expect(
      page.getByText(/Open a repository|No runs|inspect|preview/i).first(),
    ).toBeVisible();

    await openSection(page, "Codegen Stream");
    await expect(
      page.getByText(/No active codegen stream|Open a repository|stopped|waiting/i).first(),
    ).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });

  test("navigates across analysis views and checks coverage/gap affordances when available", async ({
    page,
  }) => {
    // Intent: verify analysis sections are reachable and, when data exists, expose gap-to-generation affordances.
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);

    await openSection(page, "Coverage & Gaps");

    const generateForGapButton = page.getByRole("button", { name: /Generate/i });
    if (await generateForGapButton.isVisible().catch(() => false)) {
      await expect(generateForGapButton).toBeEnabled();
    } else {
      await expect(
        page.getByText(/Open a repository to view coverage|Loading coverage…|No coverage report found/i),
      ).toBeVisible();
    }

    await openSection(page, "Memory Map");
    await expect(
      page.getByText(/No memory map found|Open a repository to view the memory map\./),
    ).toBeVisible();

    await openSection(page, "Flow Graph");
    await expect(
      page.getByText(/No flow graph found|Open a repository to view the flow graph\./),
    ).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });
});