// Generated by playwright-god (mode=static, archetype=static-site, confidence=0.25)
import { test, expect, Page } from "@playwright/test";

type ConsoleEntry = { type: string; text: string };

async function attachPageDiagnostics(page: Page) {
  const consoleMessages: ConsoleEntry[] = [];
  const pageErrors: string[] = [];

  page.on("console", (msg) => {
    consoleMessages.push({ type: msg.type(), text: msg.text() });
  });

  page.on("pageerror", (err) => {
    pageErrors.push(String(err));
  });

  return {
    consoleMessages,
    pageErrors,
    assertNoPageErrors: async () => {
      expect(pageErrors, `Unexpected page errors:\n${pageErrors.join("\n")}`).toEqual([]);
    },
  };
}

async function gotoDesktopShell(page: Page) {
  await page.goto("/");
  await page.waitForLoadState("domcontentloaded");
  await expect(page.getByRole("button", { name: "Repository", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Memory Map", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Flow Graph", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Coverage & Gaps", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Generation", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Codegen Stream", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Dry Run / Inspect", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Audit Log", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Settings", exact: true })).toBeVisible();
}

async function openSection(page: Page, name: string) {
  await page.getByRole("button", { name, exact: true }).click();
  await expect(page.getByRole("heading", { name })).toBeVisible();
}

test.describe("Playwright God desktop shell end-to-end", () => {
  test("navigates the desktop shell and validates repository selection and empty-state CTAs", async ({
    page,
  }) => {
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);

    await openSection(page, "Repository");
    await expect(
      page.getByText(/Select a repository to inspect index status|Indexing is required before Memory Map and RAG search can load\./),
    ).toBeVisible();

    const openRepoButton = page.getByRole("button", { name: "Open Repository…" });
    await expect(openRepoButton).toBeVisible();

    const runIndexButton = page.getByRole("button", { name: "Run Index" });
    if (await runIndexButton.isVisible().catch(() => false)) {
      await expect(runIndexButton).toBeDisabled();
    }

    await openSection(page, "Memory Map");
    await expect(
      page.getByText(/No memory map found|Open a repository from the Repository tab to view its memory map\./),
    ).toBeVisible();

    const memoryMapRunIndex = page.getByRole("button", { name: "Run Index" });
    if (await memoryMapRunIndex.isVisible().catch(() => false)) {
      await expect(memoryMapRunIndex).toBeDisabled();
    }

    await openSection(page, "Flow Graph");
    await expect(
      page.getByText(/No flow graph found|Open a repository to view its flow graph\./),
    ).toBeVisible();

    await openSection(page, "Coverage & Gaps");
    await expect(
      page.getByText(/Open a repository to view coverage|Loading coverage…|No coverage report found/i),
    ).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });

  test("opens settings and verifies provider resolution and secret-related controls are present", async ({
    page,
  }) => {
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);
    await openSection(page, "Settings");

    await expect(page.getByText(/provider/i).first()).toBeVisible();
    await expect(page.getByText(/model/i).first()).toBeVisible();
    await expect(page.getByText(/OpenAI|Anthropic|Gemini|Template/i).first()).toBeVisible();
    await expect(
      page.getByText(/effective|resolved|source|repo-dotenv|process env|settings/i).first(),
    ).toBeVisible();

    const saveButton = page.getByRole("button", { name: /save/i });
    if (await saveButton.isVisible().catch(() => false)) {
      await expect(saveButton).toBeEnabled();
    }

    const resetButton = page.getByRole("button", { name: /reset/i });
    if (await resetButton.isVisible().catch(() => false)) {
      await expect(resetButton).toBeVisible();
    }

    await diagnostics.assertNoPageErrors();
  });

  test("covers generation workflow states including disabled-without-repo, prompt entry, and pipeline controls", async ({
    page,
  }) => {
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);
    await openSection(page, "Generation");

    await expect(
      page.getByText(/Select a repository in the Repository section to enable the pipeline\./),
    ).toBeVisible();

    const description = page.getByRole("textbox", {
      name: /Description \(optional\)/i,
    });
    await expect(description).toBeVisible();
    await expect(description).toHaveAttribute(
      "placeholder",
      /What should the next generated test cover\?/,
    );

    await description.fill("login flow");
    await expect(description).toHaveValue("login flow");

    const runPipeline = page.getByRole("button", { name: /Run Pipeline|Running\.\.\./ });
    await expect(runPipeline).toBeDisabled();

    const cancelButton = page.getByRole("button", { name: /Cancel/i });
    if (await cancelButton.isVisible().catch(() => false)) {
      await expect(cancelButton).toBeDisabled();
    }

    await expect(page.getByText(/idle|running|failed|cancelled|succeeded/i).first()).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });

  test("covers RAG search empty state and search form visibility", async ({ page }) => {
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);

    await openSection(page, "RAG Search");
    await expect(page.getByText(/Open a repository to search its index\./i)).toBeVisible();

    const runIndexButton = page.getByRole("button", { name: "Run Index" });
    if (await runIndexButton.isVisible().catch(() => false)) {
      await expect(runIndexButton).toBeDisabled();
    }

    const searchButton = page.getByRole("button", { name: /Search/i });
    if (await searchButton.isVisible().catch(() => false)) {
      await expect(searchButton).toBeEnabled();
    }

    await diagnostics.assertNoPageErrors();
  });

  test("validates audit log visibility and no-runs state", async ({ page }) => {
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);
    await openSection(page, "Audit Log");

    await expect(page.getByText(/Open a repository to view its audit log\./i)).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });

  test("validates inspect and output-oriented sections render stable empty or loading states", async ({
    page,
  }) => {
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);

    await openSection(page, "Dry Run / Inspect");
    await expect(page.getByText(/Open a repository to inspect it\./i)).toBeVisible();

    await openSection(page, "Codegen Stream");
    await expect(
      page.getByText(/No active codegen stream|Open a repository to tail codegen output\.|stopped|waiting/i).first(),
    ).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });

  test("navigates across analysis views and checks coverage/gap affordances when available", async ({
    page,
  }) => {
    const diagnostics = await attachPageDiagnostics(page);

    await gotoDesktopShell(page);

    await openSection(page, "Coverage & Gaps");

    const generateForGapButton = page.getByRole("button", { name: /Generate/i });
    if (await generateForGapButton.isVisible().catch(() => false)) {
      await expect(generateForGapButton).toBeEnabled();
    } else {
      await expect(
        page.getByText(/Open a repository to view coverage|Loading coverage…|No coverage report found/i),
      ).toBeVisible();
    }

    await openSection(page, "Memory Map");
    await expect(
      page.getByText(/No memory map found|Open a repository from the Repository tab to view its memory map\./),
    ).toBeVisible();

    await openSection(page, "Flow Graph");
    await expect(
      page.getByText(/No flow graph found|Open a repository to view its flow graph\./),
    ).toBeVisible();

    await diagnostics.assertNoPageErrors();
  });
});